-- CreateEnum
CREATE TYPE "LeadStatus" AS ENUM ('NEW', 'CONTACTED', 'ENROLLED', 'ARCHIVED');

-- CreateTable
CREATE TABLE "AdminUser" ("id" TEXT NOT NULL, "login" TEXT NOT NULL, "name" TEXT NOT NULL, "passwordHash" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "AdminUser_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Coach" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "role" TEXT NOT NULL, "rank" TEXT NOT NULL, "bio" TEXT NOT NULL, "imageUrl" TEXT NOT NULL, "experience" INTEGER NOT NULL, "achievements" TEXT NOT NULL, "order" INTEGER NOT NULL DEFAULT 0, "isPublished" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Coach_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Program" ("id" TEXT NOT NULL, "title" TEXT NOT NULL, "slug" TEXT NOT NULL, "ageRange" TEXT NOT NULL, "level" TEXT NOT NULL, "description" TEXT NOT NULL, "duration" TEXT NOT NULL, "price" TEXT NOT NULL, "accent" TEXT NOT NULL DEFAULT 'lime', "order" INTEGER NOT NULL DEFAULT 0, "isPublished" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Program_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Branch" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "address" TEXT NOT NULL, "district" TEXT NOT NULL, "phone" TEXT NOT NULL, "hours" TEXT NOT NULL, "mapUrl" TEXT, "order" INTEGER NOT NULL DEFAULT 0, "isPublished" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Branch_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Schedule" ("id" TEXT NOT NULL, "dayOfWeek" TEXT NOT NULL, "startTime" TEXT NOT NULL, "endTime" TEXT NOT NULL, "groupName" TEXT NOT NULL, "spotsLeft" INTEGER NOT NULL DEFAULT 0, "coachId" TEXT NOT NULL, "programId" TEXT NOT NULL, "branchId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Schedule_pkey" PRIMARY KEY ("id"));
CREATE TABLE "StudentAchievement" ("id" TEXT NOT NULL, "studentName" TEXT NOT NULL, "title" TEXT NOT NULL, "event" TEXT NOT NULL, "date" TIMESTAMP(3) NOT NULL, "place" TEXT NOT NULL, "imageUrl" TEXT, "description" TEXT NOT NULL, "order" INTEGER NOT NULL DEFAULT 0, "isPublished" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "StudentAchievement_pkey" PRIMARY KEY ("id"));
CREATE TABLE "NewsPost" ("id" TEXT NOT NULL, "title" TEXT NOT NULL, "slug" TEXT NOT NULL, "excerpt" TEXT NOT NULL, "content" TEXT NOT NULL, "category" TEXT NOT NULL, "imageUrl" TEXT NOT NULL, "publishedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "isPublished" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "NewsPost_pkey" PRIMARY KEY ("id"));
CREATE TABLE "GalleryImage" ("id" TEXT NOT NULL, "title" TEXT NOT NULL, "alt" TEXT NOT NULL, "imageUrl" TEXT NOT NULL, "category" TEXT NOT NULL, "order" INTEGER NOT NULL DEFAULT 0, "isPublished" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "GalleryImage_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Lead" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "phone" TEXT NOT NULL, "studentAge" INTEGER NOT NULL, "level" TEXT NOT NULL, "program" TEXT NOT NULL, "comment" TEXT, "status" "LeadStatus" NOT NULL DEFAULT 'NEW', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Lead_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SiteSettings" ("id" TEXT NOT NULL DEFAULT 'main', "schoolName" TEXT NOT NULL, "shortName" TEXT NOT NULL, "tagline" TEXT NOT NULL, "description" TEXT NOT NULL, "phone" TEXT NOT NULL, "email" TEXT NOT NULL, "address" TEXT NOT NULL, "telegram" TEXT, "instagram" TEXT, "whatsapp" TEXT, "foundedYear" INTEGER NOT NULL, "studentsCount" INTEGER NOT NULL, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "SiteSettings_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "AdminUser_login_key" ON "AdminUser"("login");
CREATE UNIQUE INDEX "Program_slug_key" ON "Program"("slug");
CREATE UNIQUE INDEX "NewsPost_slug_key" ON "NewsPost"("slug");

ALTER TABLE "Schedule" ADD CONSTRAINT "Schedule_coachId_fkey" FOREIGN KEY ("coachId") REFERENCES "Coach"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Schedule" ADD CONSTRAINT "Schedule_programId_fkey" FOREIGN KEY ("programId") REFERENCES "Program"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Schedule" ADD CONSTRAINT "Schedule_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE CASCADE ON UPDATE CASCADE;
